# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apex_manifest.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'apex_manifest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61pex_manifest.proto\x12\napex.proto\"\xf1\x03\n\x0c\x41pexManifest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12\x16\n\x0epreInstallHook\x18\x03 \x01(\t\x12\x1b\n\x0fpostInstallHook\x18\x04 \x01(\tB\x02\x18\x01\x12\x13\n\x0bversionName\x18\x05 \x01(\t\x12\x0e\n\x06noCode\x18\x06 \x01(\x08\x12\x19\n\x11provideNativeLibs\x18\x07 \x03(\t\x12\x19\n\x11requireNativeLibs\x18\x08 \x03(\t\x12\x0f\n\x07jniLibs\x18\t \x03(\t\x12\x1d\n\x15requireSharedApexLibs\x18\n \x03(\t\x12\x1d\n\x15provideSharedApexLibs\x18\x0b \x01(\x08\x12\x46\n\rcapexMetadata\x18\x0c \x01(\x0b\x32/.apex.proto.ApexManifest.CompressedApexMetadata\x12 \n\x18supportsRebootlessUpdate\x18\r \x01(\x08\x12\x13\n\x0bvndkVersion\x18\x0e \x01(\t\x12\x1b\n\x0fvendorBootstrap\x18\x0f \x01(\x08\x42\x02\x18\x01\x12\x11\n\tbootstrap\x18\x10 \x01(\x08\x1a\x34\n\x16\x43ompressedApexMetadata\x12\x1a\n\x12originalApexDigest\x18\x01 \x01(\tB\x1a\n\x10\x63om.android.apexB\x06Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apex_manifest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.android.apexB\006Protos'
  _globals['_APEXMANIFEST'].fields_by_name['postInstallHook']._loaded_options = None
  _globals['_APEXMANIFEST'].fields_by_name['postInstallHook']._serialized_options = b'\030\001'
  _globals['_APEXMANIFEST'].fields_by_name['vendorBootstrap']._loaded_options = None
  _globals['_APEXMANIFEST'].fields_by_name['vendorBootstrap']._serialized_options = b'\030\001'
  _globals['_APEXMANIFEST']._serialized_start=36
  _globals['_APEXMANIFEST']._serialized_end=533
  _globals['_APEXMANIFEST_COMPRESSEDAPEXMETADATA']._serialized_start=481
  _globals['_APEXMANIFEST_COMPRESSEDAPEXMETADATA']._serialized_end=533
# @@protoc_insertion_point(module_scope)
